
services:
  db-barbearia:
    container_name: "db-barbearia"
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    networks:
      - "net-barbearia"
    volumes:
      - "vol-barbearia:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: "always"
    
  redis-barbearia:
    container_name: "redis-barbearia"
    image: "redis:7.0"
    ports:
      - "6379:6379"
    networks:
      - "net-barbearia"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: "always"
  api-barbearia:
    container_name: "api-barbearia"
    build:
      context: ./
      dockerfile: Dockerfile
    image: "api-barbearia:5.0"
    ports:
      - "80:8000"
    networks:
      - "net-barbearia"
    volumes:
      - "./:/app"
    depends_on:
      - redis-barbearia
      - db-barbearia
    env_file:
      - ./.env
    restart: "always"
  queue:
    container_name: "queue-barbearia"
    image: "api-barbearia:5.0"
    ports:
      - "5040:5040"
    networks:
      - "net-barbearia"
    depends_on:
      - "api-barbearia"
    command: ["php","artisan", "queue:work"]

  scheduler:
    container_name: "scheduler-barbearia"
    image: "api-barbearia:5.0"
    ports:
      - "4080:4080"
    networks:
      - "net-barbearia"
    depends_on:
      - "api-barbearia"
    command: ["php","artisan", "scheduler:cron"]

volumes:
  vol-barbearia: {}

networks:
  net-barbearia:
    driver: "bridge" 