
version: "3.9"

services:
  app:
    container_name: api-barbearia
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www/html   # ðŸ”¥ cÃ³digo ao vivo (sem rebuild)

    env_file:
      - .env

    networks:
      - net-barbearia

networks:
  net-barbearia:
    external: true
