
services:
  db-barbearia:
    container_name: "db-barbearia"
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    networks:
      - "net-barbearia"
    volumes:
      - "vol-barbearia:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: "always"
    
  redis-barbearia:
    container_name: "redis-barbearia"
    image: "redis:7.0"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - "net-barbearia"
    restart: "always"

  api-barbearia:
    container_name: "api-barbearia"
    build:
      context: ./
      dockerfile: Dockerfile
    image: "api-barbearia:5.0"
    ports:
      - "5400:8000"
    networks:
      - "net-barbearia"
    volumes:
      - "./:/app"
    depends_on:
      - "redis-barbearia"
      - "db-barbearia"
      - "apache-proxy"
    env_file:
      - ./.env
    restart: "always"

  apache-proxy:
    container_name: "apache-proxy"
    image: "httpd:latest"
    ports:
      - "8080:80"
    volumes:
      - ./proxy.conf:/usr/local/apache2/conf/extra/proxy.conf
    command: >
      sh -c "echo 'Include conf/extra/proxy.conf' >> /usr/local/apache2/conf/httpd.conf
      && httpd-foreground"
    networks:
      - "net-barbearia"
    restart: "always"
  queue:
    container_name: "queue-barbearia"
    image: "api-barbearia:5.0"
    ports:
      - "5040:5040"
    networks:
      - "net-barbearia"
    depends_on:
      - "api-barbearia"
    command: ["php","artisan", "queue:work"]

  scheduler:
    container_name: "scheduler-barbearia"
    image: "api-barbearia:5.0"
    ports:
      - "4080:4080"
    networks:
      - "net-barbearia"
    depends_on:
      - "api-barbearia"
    command: ["php","artisan", "scheduler:cron"]

volumes:
  vol-barbearia: {}

networks:
  net-barbearia:
    driver: "bridge" 